name: CI Demo

on:
  push:
    branches["main"]
  pull_request:
    branches["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Compilar con Maven
      run: mvn -B package --file pom.xml

    - name: Ejecutar pruebas
      run: mvn test

    
